### PR TITLE
fix activation errors

### PR DESCRIPTION
**Pull request by absap**
a lot of namespace and renaming fixes
not a working version at all, but it's activatable

### CODE REVIEW

**Comment by larshp** [comment]
suggest just ignore the errors from abaplint for now

**Comment by absap** [comment]
> suggest just ignore the errors from abaplint for now

Yepp, will be one of the next steps

**Comment by larshp** [comment]
plus we need to adjust it to whats needed

**Comment by absap** [comment]
Also runnable with the latest UI version - not everything tested, but all repositories of the OP system are shown

**Pull request merged**
